### ISSUE TITLE
Make Web-app without the need to have a Car Thing

### ISSUE THREAD

**Issue by Jinansh230705** [Merlin04/superbird-webapp#3]
Hey, You should make this web app/ OS  independent of car thing as it will open the possibilities of flashing it to Raspberry Pi,
For someone who wants to make their own diy Car Thing
So, if possible port this web app to run on all devices

**Comment by SoCuul** [comment]
> Hey, You should make this web app/ OS independent of car thing as it will open the possibilities of flashing it to Raspberry Pi, For someone who wants to make their own diy Car Thing So, if possible port this web app to run on all devices

Unfortunately that's not possible, as the web app is only part of the software that makes car thing work. It relies on other software to facilitate the bluetooth/mfi data transmission, which makes it a *much* bigger task to get working on something else.

**Comment by Jinansh230705** [comment]
> > Hey, You should make this web app/ OS independent of car thing as it will open the possibilities of flashing it to Raspberry Pi, For someone who wants to make their own diy Car Thing So, if possible port this web app to run on all devices
> 
> Unfortunately that's not possible, as the web app is only part of the software that makes car thing work. It relies on other software to facilitate the bluetooth/mfi data transmission, which makes it a *much* bigger task to get working on something else.

So can't we port the entire OS?

**Comment by SoCuul** [comment]
> > > Hey, You should make this web app/ OS independent of car thing as it will open the possibilities of flashing it to Raspberry Pi, For someone who wants to make their own diy Car Thing So, if possible port this web app to run on all devices
> > 
> > 
> > Unfortunately that's not possible, as the web app is only part of the software that makes car thing work. It relies on other software to facilitate the bluetooth/mfi data transmission, which makes it a _much_ bigger task to get working on something else.
> 
> So can't we port the entire OS?

Not without a large amount of dedicated effort

**Comment by Jinansh230705** [comment]
> > > > Hey, You should make this web app/ OS independent of car thing as it will open the possibilities of flashing it to Raspberry Pi, For someone who wants to make their own diy Car Thing So, if possible port this web app to run on all devices
> > > 
> > > 
> > > Unfortunately that's not possible, as the web app is only part of the software that makes car thing work. It relies on other software to facilitate the bluetooth/mfi data transmission, which makes it a _much_ bigger task to get working on something else.
> > 
> > So can't we port the entire OS?
> 
> Not without a large amount of dedicated effort

Oh, thanks for your help
I think it's too much work then 
Maybe I would make a similar looking Web-app for Android that can be flashed on raspberry pi
